# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b965dcf2ebb3dd63eb7914c5abc49d6b83d924098b0726f54a43b1749993fef4a409f5ce55ad5e545ddc22f31373dc859feeaa5433610bd5eabbb6613d43f2d

test:
  secret_key_base: 18feb2c94ef4e499ee852c982b6171c2db81c12526bbfca5ebdb3a2cec854ce880d67fa5eb1ebdb3b0d57cd675cc3db1ea2bd3f56992ab3bf97ca6f2949ed8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
